version: "3.8"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.1.5
    container_name: elasticsearch
    environment:
     - xpack.security.enabled=false
     - xpack.security.enrollment.enabled=false
     - discovery.type=single-node
     - ES_JAVA_OPTS= -Xms5g -Xmx5g
    ports:
      - "9200:9200"
      - "9300:9300"
